# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aed76ac6ca8a2c8820b619557d85368a08d58f17344f601a8ba68ca5af07870d8e5b1e5f8fc6260b0fee37151dd1bba69a6c7d4f80c6722809d9fda224c45507

test:
  secret_key_base: c5eb4c2ba95f3dc8d7f4958a20ef6714d0bd3ad8ed522e2f4142ae042cfae271d15e968e78feee13f8228175a8d19623fe504c546bc734374611c473231f77b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
